"""Ingest MongoDB documents into Milvus as dense + sparse chunks.

Pipeline per doc:
    1. Load from Mongo (projection limited to spec.text_fields + metadata)
    2. Chunk (Markdown-aware, atomic-regex-guarded, recursive char splitter)
    3. Embed each chunk via TEI (batched 32–64 per HTTP round-trip)
    4. Upsert to Milvus with deterministic chunk_id → idempotent re-ingest

Design notes
------------
• Reuses ``kb_service.CollectionSpec`` / ``SPECS_LIST`` / ``_extract_*`` so the
  Mongo → canonical transformation is single-source-of-truth.
• Chunk_id is sha256(doc_id || chunk_index || chunk_hash)[:24] — stable across
  re-embeds, safe for Milvus PK.
• BM25 sparse_vector is auto-generated by Milvus Function (see
  ``init_kb_chunks.py``) — we do NOT ship sparse vectors from the client.
• LangChain MarkdownHeaderTextSplitter first, then RecursiveCharacterTextSplitter
  inside each section.
• Atomic regex guards stop the splitter from breaking tickers / quarters / %.
"""
from __future__ import annotations

# Proxy bypass for localhost gRPC (Clash 7890 otherwise intercepts).
import os
os.environ.setdefault("no_proxy", "127.0.0.1,localhost,jumpbox,116.239.28.36,192.168.31.0/24")
os.environ.setdefault("NO_PROXY", "127.0.0.1,localhost,jumpbox,116.239.28.36,192.168.31.0/24")

import argparse
import asyncio
import hashlib
import logging
import re
import sys
import time
from dataclasses import dataclass
from typing import Any, AsyncIterator, Iterable

from langchain_text_splitters import (
    MarkdownHeaderTextSplitter,
    RecursiveCharacterTextSplitter,
)
from pymilvus import MilvusClient
from pymongo import MongoClient

from backend.app.config import get_settings
from backend.app.services import tei_client
from backend.app.services.kb_service import (
    SPECS_BY_KEY,
    SPECS_LIST,
    CollectionSpec,
    _extract_date,
    _extract_institution,
    _extract_text,
    _extract_tickers,
    mongo_db_name_for,
)

logger = logging.getLogger(__name__)


# ── Chunking constants ─────────────────────────────────────────────

CHILD_TOKENS = 480           # target tokens per child chunk
CHILD_OVERLAP = 64           # token overlap
CHAR_PER_TOKEN_CJK = 1.8     # heuristic: 1 token ≈ 1.8 CJK chars (Qwen tokenizer)
CHAR_PER_TOKEN_EN = 4.0      # ≈ 4 chars per EN token

CHILD_CHARS_CJK = int(CHILD_TOKENS * CHAR_PER_TOKEN_CJK)   # ≈ 864
CHILD_CHARS_EN = int(CHILD_TOKENS * CHAR_PER_TOKEN_EN)     # ≈ 1920
OVERLAP_CHARS_CJK = int(CHILD_OVERLAP * CHAR_PER_TOKEN_CJK)  # ≈ 115
OVERLAP_CHARS_EN = int(CHILD_OVERLAP * CHAR_PER_TOKEN_EN)    # ≈ 256

PARENT_CHARS_MAX = 1800 * int(CHAR_PER_TOKEN_EN)   # 1800 tokens parent upper bound

SHORT_DOC_MIN_CHARS = 120    # below this → single chunk, no splitting

# Atomic regex: splitter must not cut these mid-token.
ATOMIC_PATTERNS = [
    # Stock codes: trailing boundary dropped because CJK chars count as word
    # chars under Unicode \b, so "NVDA.US股价" wouldn't match with trailing \b.
    r"(?<![A-Z0-9])[A-Z]{1,5}\.(?:US|HK|SH|SZ|BJ|TW)(?![A-Z0-9.])",
    r"(?<!\d)\d{4,6}\.(?:US|HK|SH|SZ|BJ|TW)(?!\d)",
    # Quarter: "2025Q3", "2025 Q3", "2025-Q3".
    r"(?<!\d)\d{4}[- ]?Q[1-4](?!\d)",
    # Fiscal period: FY25, FY25E, Q3E.
    r"(?<![A-Z0-9])(?:FY|Q)\d{1,2}E?(?![A-Z0-9])",
    # Numeric literals with decimals / percent.
    r"\d+[\.,]\d+%?",
    # Money with CN units or EN multipliers.
    r"[¥$€£]\s?\d+(?:[.,]\d+)?(?:亿|万|B|M|K)?",
]
_ATOMIC_RE = re.compile("|".join(ATOMIC_PATTERNS))


# ── Language detection ────────────────────────────────────────────


def _detect_lang(text: str) -> str:
    if not text:
        return "zh"
    sample = text[:500]
    cjk = sum(1 for c in sample if "一" <= c <= "鿿")
    if cjk / max(len(sample), 1) >= 0.30:
        return "zh"
    return "en"


# ── Chunker ────────────────────────────────────────────────────────


@dataclass
class Chunk:
    chunk_index: int
    char_start: int
    char_end: int
    chunk_text: str
    parent_index: int
    parent_text: str


def _markdown_sections(text: str) -> list[tuple[int, str]]:
    """Split on Markdown H1-H4 headings. Returns (offset, section_text) pairs.

    If no headings are present, returns the whole text as a single section.
    """
    splitter = MarkdownHeaderTextSplitter(
        headers_to_split_on=[("#", "h1"), ("##", "h2"), ("###", "h3"), ("####", "h4")],
        strip_headers=False,
    )
    try:
        docs = splitter.split_text(text)
    except Exception:
        return [(0, text)]
    if not docs:
        return [(0, text)]
    # MarkdownHeaderTextSplitter strips/reformats, which breaks offset tracking.
    # For offset correctness we fall back to regex-locating each section's
    # content back in the original string.
    out: list[tuple[int, str]] = []
    search_from = 0
    for d in docs:
        content = d.page_content
        stripped = content.strip()
        if not stripped:
            continue
        # Find the first N non-whitespace chars in the raw text starting from
        # search_from; pick a medium-length signature to minimize false hits.
        sig = stripped[:30]
        idx = text.find(sig, search_from)
        if idx < 0:
            # Fallback: append from where we left off
            idx = search_from
        out.append((idx, content))
        search_from = idx + len(content)
    if not out:
        return [(0, text)]
    return out


def _guarded_split(text: str, chunk_size: int, overlap: int) -> list[tuple[int, str]]:
    """Split `text` into chunks of ~chunk_size chars with `overlap` chars overlap,
    never breaking an atomic regex span. Returns [(offset_into_text, chunk_text)].
    """
    splitter = RecursiveCharacterTextSplitter(
        chunk_size=chunk_size,
        chunk_overlap=overlap,
        separators=["\n\n", "\n", "。", "！", "？", "；", ". ", "! ", "? ", "; ", "，", ", ", " ", ""],
        keep_separator=True,
    )
    raw = splitter.split_text(text)

    # Re-anchor offsets: LangChain doesn't return them, so locate each piece in
    # the source. Overlap means the same chars appear in adjacent chunks; we
    # disambiguate by searching forward from the previous end.
    out: list[tuple[int, str]] = []
    cursor = 0
    for piece in raw:
        if not piece.strip():
            continue
        # Search within a reasonable window around cursor
        start = text.find(piece, max(0, cursor - len(piece)))
        if start < 0:
            start = cursor
        end = start + len(piece)
        # Atomic guard: if a match of an atomic pattern straddles the start or
        # end boundary, nudge the boundary outward to include the whole token.
        piece, start, end = _repair_atomic_boundary(text, piece, start, end)
        out.append((start, piece))
        cursor = end
    return out


def _repair_atomic_boundary(
    full_text: str, piece: str, start: int, end: int
) -> tuple[str, int, int]:
    """If an atomic pattern match straddles start or end, widen the chunk to
    include the whole atomic span. Cheap: only looks in a small window."""
    window_l = max(0, start - 12)
    window_r = min(len(full_text), end + 12)

    for m in _ATOMIC_RE.finditer(full_text[window_l:window_r]):
        m_abs_start = window_l + m.start()
        m_abs_end = window_l + m.end()
        if m_abs_start < start <= m_abs_end:
            start = m_abs_start
        if m_abs_start < end < m_abs_end:
            end = m_abs_end
    return full_text[start:end], start, end


def chunk_document(text: str, *, lang: str | None = None) -> list[Chunk]:
    """Produce child chunks with parent-section anchors for a single document.

    • Short docs (< SHORT_DOC_MIN_CHARS) → single chunk, no splitting.
    • Long docs → markdown sections → guarded child splits.
    """
    if not text or not text.strip():
        return []

    if lang is None:
        lang = _detect_lang(text)
    child_chars = CHILD_CHARS_CJK if lang == "zh" else CHILD_CHARS_EN
    overlap_chars = OVERLAP_CHARS_CJK if lang == "zh" else OVERLAP_CHARS_EN

    if len(text) <= SHORT_DOC_MIN_CHARS:
        return [Chunk(
            chunk_index=0,
            char_start=0,
            char_end=len(text),
            chunk_text=text.strip(),
            parent_index=0,
            parent_text=text.strip(),
        )]

    sections = _markdown_sections(text)
    child_idx = 0
    chunks: list[Chunk] = []
    for parent_idx, (p_off, p_text) in enumerate(sections):
        p_text_trimmed = p_text.strip()
        if not p_text_trimmed:
            continue
        parent_for_return = p_text_trimmed[:PARENT_CHARS_MAX]

        if len(p_text_trimmed) <= child_chars:
            # Small section → one chunk
            chunks.append(Chunk(
                chunk_index=child_idx,
                char_start=p_off,
                char_end=p_off + len(p_text),
                chunk_text=p_text_trimmed,
                parent_index=parent_idx,
                parent_text=parent_for_return,
            ))
            child_idx += 1
            continue

        # Big section → split
        pieces = _guarded_split(p_text, child_chars, overlap_chars)
        for off_in_parent, piece in pieces:
            chunks.append(Chunk(
                chunk_index=child_idx,
                char_start=p_off + off_in_parent,
                char_end=p_off + off_in_parent + len(piece),
                chunk_text=piece.strip(),
                parent_index=parent_idx,
                parent_text=parent_for_return,
            ))
            child_idx += 1
    return chunks


# ── Per-doc Milvus row builder ────────────────────────────────────


def _vector_doc_id(db: str, collection: str, mongo_id: Any) -> str:
    return f"{db}:{collection}:{str(mongo_id)}"


def _chunk_id(doc_id: str, chunk_index: int, chunk_text: str) -> str:
    ch = hashlib.sha256(chunk_text.encode("utf-8")).hexdigest()[:16]
    return hashlib.sha256(f"{doc_id}|{chunk_index}|{ch}".encode("utf-8")).hexdigest()[:24]


def _chunk_hash(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def _snippet(text: str, maxlen: int = 240) -> str:
    t = (text or "").strip().replace("\n", " ")
    return t if len(t) <= maxlen else t[:maxlen - 1] + "…"


def build_rows_for_doc(spec: CollectionSpec, doc: dict) -> list[dict]:
    """Build Milvus row dicts for a single Mongo doc. Does NOT run embeddings.

    Returns an empty list if the doc has no usable content text.
    """
    text = _extract_text(spec, doc)
    if not text or not text.strip():
        return []

    title = str(doc.get(spec.title_field) or "")[:512]
    date_str, release_ms = _extract_date(spec, doc)
    institution = _extract_institution(spec, doc)
    tickers = _extract_tickers(spec, doc)[:32]
    url = str(doc.get(spec.url_field) or "") if spec.url_field else ""

    mongo_id = doc["_id"]
    doc_id = _vector_doc_id(spec.db, spec.collection, mongo_id)

    lang = _detect_lang(text)
    chunks = chunk_document(text, lang=lang)

    s = get_settings()
    rows: list[dict] = []
    for ch in chunks:
        c_hash = _chunk_hash(ch.chunk_text)
        rows.append({
            "chunk_id": _chunk_id(doc_id, ch.chunk_index, ch.chunk_text),
            "doc_id": doc_id,
            "db": spec.db,
            "collection": spec.collection,
            "source_type": "kb",
            "doc_type": spec.doc_type,
            "doc_type_cn": spec.doc_type_cn,
            "title": title,
            "release_time_ms": int(release_ms) if release_ms else 0,
            "tickers": tickers,
            "chunk_index": ch.chunk_index,
            "char_start": ch.char_start,
            "char_end": ch.char_end,
            "chunk_hash": c_hash,
            "parent_id": f"{doc_id}:p{ch.parent_index}",
            "parent_text": ch.parent_text[:65535],
            "lang": lang,
            "chunk_text": ch.chunk_text[:65535],
            "snippet_text": _snippet(ch.chunk_text, 240),
            "url": url[:1024],
            "embedding_model_version": s.embedding_model_version,
        })
    return rows


# ── Async cursor helper ────────────────────────────────────────────────
# Sync pymongo cursors block the event loop on every `next()` (each one is a
# network read; over a 40k-doc collection the loop stays pinned for minutes
# and FastAPI requests time out). Drain the cursor on a worker thread instead
# and yield to the loop in batches — small enough that other tasks (chat
# requests, quote warmer) get scheduled regularly, large enough that the
# thread-hop overhead stays negligible.
async def _aiter_cursor(cursor, batch_size: int = 200) -> AsyncIterator[dict]:
    def _next_batch() -> list[dict]:
        out: list[dict] = []
        try:
            for _ in range(batch_size):
                out.append(next(cursor))
        except StopIteration:
            pass
        return out
    while True:
        batch = await asyncio.to_thread(_next_batch)
        if not batch:
            return
        # The consumer's per-doc work (build_rows_for_doc → markdown chunking,
        # hashing, Milvus prefetch lookups) is sync. Without an explicit await
        # every few docs the loop stays pinned for the whole 200-doc batch —
        # tens of seconds at observed rates — and unrelated FastAPI handlers
        # (sentimentrader cards, quote warmer) time out. sleep(0) is just a
        # tick yield, not a real sleep.
        for i, doc in enumerate(batch):
            yield doc
            if (i & 7) == 7:
                await asyncio.sleep(0)


# ── Milvus helpers (sync, wrapped in asyncio.to_thread for async callers) ──


def _escape_milvus_str(v: str) -> str:
    """Safe VARCHAR literal for Milvus filter expressions."""
    return v.replace("\\", "\\\\").replace('"', '\\"')


def _existing_chunks_for_doc(mv: MilvusClient, collection: str, doc_id: str) -> list[dict]:
    """Return all chunks currently in Milvus for one doc_id (<=1000 chunks/doc).

    Per-doc query. Used by `delete_doc` and ad-hoc tools. The main ingest
    loop uses ``_prefetch_existing_by_doc`` instead to avoid N Milvus
    round-trips.
    """
    try:
        return mv.query(
            collection_name=collection,
            filter=f'doc_id == "{_escape_milvus_str(doc_id)}"',
            output_fields=["chunk_id", "chunk_hash", "embedding_model_version"],
            limit=1024,
        )
    except Exception as e:
        logger.warning("query existing failed for %s: %s", doc_id, e)
        return []


def _prefetch_existing_by_doc(
    mv: MilvusClient, collection: str, db: str, mongo_coll: str,
) -> dict[str, list[dict]]:
    """Single-pass load of every chunk for (db, mongo_coll) into an in-memory
    dict ``{doc_id: [chunk_record, ...]}``. Used once per ingest run so the
    per-doc skip check is O(1) dict lookup instead of a Milvus round-trip.

    Memory: one (db, collection) like ``alphapai.wechat_articles`` with 40k
    chunks × ~100 bytes per record ≈ 4 MB. Fine for hundreds of collections.

    Paging: orders by chunk_id ascending. For Milvus >= 2.5 this is stable;
    we stop when a page returns fewer than PAGE rows OR produces no new
    high-water mark (safety net against infinite loops).
    """
    out: dict[str, list[dict]] = {}
    last = ""
    PAGE = 16384
    t0 = time.monotonic()
    total = 0
    while True:
        filt = f'db == "{_escape_milvus_str(db)}" and collection == "{_escape_milvus_str(mongo_coll)}"'
        if last:
            filt += f' and chunk_id > "{_escape_milvus_str(last)}"'
        try:
            page = mv.query(
                collection_name=collection,
                filter=filt,
                output_fields=["chunk_id", "doc_id", "chunk_hash",
                               "embedding_model_version"],
                limit=PAGE,
            )
        except Exception as e:
            logger.warning("prefetch existing (%s/%s) failed: %s", db, mongo_coll, e)
            break
        if not page:
            break
        total += len(page)
        for r in page:
            out.setdefault(r["doc_id"], []).append(r)
        new_last = max(r["chunk_id"] for r in page)
        if new_last == last or len(page) < PAGE:
            break
        last = new_last
    elapsed = time.monotonic() - t0
    logger.info(
        "prefetched %d existing chunks covering %d docs for %s/%s in %.1fs",
        total, len(out), db, mongo_coll, elapsed,
    )
    return out


def _delete_chunk_ids(mv: MilvusClient, collection: str, chunk_ids: set[str]) -> int:
    """Delete specific chunk_ids. Batches of 500 to stay under Milvus IN-expr limits."""
    if not chunk_ids:
        return 0
    total = 0
    ids = list(chunk_ids)
    for start in range(0, len(ids), 500):
        batch = ids[start:start + 500]
        lit = ", ".join(f'"{_escape_milvus_str(c)}"' for c in batch)
        try:
            mv.delete(collection_name=collection, filter=f'chunk_id in [{lit}]')
            total += len(batch)
        except Exception as e:
            logger.error("delete chunk_ids batch failed (%d): %s", len(batch), e)
    return total


def delete_doc(mv: MilvusClient, collection: str, doc_id: str) -> int:
    """Delete ALL chunks for a given doc_id. Returns count deleted.

    Used by:
      • The delete sweep (see sweep_deleted_docs)
      • Manual surgery: `python3 -m scripts.kb_vector remove --doc-id ...`
    """
    try:
        res = mv.delete(
            collection_name=collection,
            filter=f'doc_id == "{_escape_milvus_str(doc_id)}"',
        )
        # pymilvus returns dict with 'delete_count' on newer versions.
        if isinstance(res, dict):
            return int(res.get("delete_count", 0))
        return -1
    except Exception as e:
        logger.error("delete_doc failed for %s: %s", doc_id, e)
        return 0


# ── Sync state / lease ──────────────────────────────────────────
#
# Sync state lives in a separate Mongo instance from the crawler corpus:
# `ta-mongo-state` container on `mongodb://localhost:27017` (no auth) →
# database `kb_vector_sync`. Keeping the lease/tombstone store split from
# the crawler corpus (`ta-mongo-crawl` :27018) means the poller owns its
# own ops space and no scraper can stomp the lease docs by accident.
# Originally introduced in the 2026-04-23 remote-Mongo era when the remote
# `u_spider` account had no `admin`-DB write permission; the split is
# kept after the 2026-04-26 back-migration because it remains the cleaner
# separation of concerns.


SYNC_STATE_URI = os.environ.get("KB_VECTOR_STATE_URI", "mongodb://localhost:27017")
SYNC_STATE_DB = os.environ.get("KB_VECTOR_STATE_DB", "kb_vector_sync")


def _state_client() -> MongoClient:
    """Local Mongo client for lease/state/tombstone metadata."""
    return MongoClient(SYNC_STATE_URI, serverSelectionTimeoutMS=5000)


def _sync_state_key(spec: CollectionSpec) -> str:
    return f"{spec.db}/{spec.collection}"


def acquire_lease(mc: MongoClient, spec: CollectionSpec, ttl_seconds: int = 7200) -> bool:
    """Atomic CAS on admin.vector_sync_state. Returns True iff this process
    now holds the lease. A stale lease (older than TTL) is forcibly taken.

    Implementation note: MongoDB's find_one_and_update(upsert=True) raises
    DuplicateKeyError when the filter does NOT match an existing doc of the
    same _id (because upsert tries to INSERT a duplicate). We handle three
    cases explicitly:

    1. No doc for this key → insert via upsert.
    2. Doc exists, lease free or stale → atomic CAS succeeds.
    3. Doc exists, lease held and fresh → return False (caller should skip).
    """
    from pymongo.errors import DuplicateKeyError

    key = _sync_state_key(spec)
    now_ms = int(time.time() * 1000)
    stale_before_ms = now_ms - ttl_seconds * 1000
    coll = _state_client()[SYNC_STATE_DB]["vector_sync_state"]

    # Fast path: update existing doc if lease is free or stale.
    result = coll.find_one_and_update(
        {
            "_id": key,
            "$or": [
                {"in_progress": {"$ne": True}},
                {"lease_at_ms": {"$lt": stale_before_ms}},
                {"lease_at_ms": {"$exists": False}},
            ],
        },
        {"$set": {"in_progress": True, "lease_at_ms": now_ms, "lease_pid": os.getpid()}},
        upsert=False,
        return_document=True,
    )
    if result is not None and result.get("lease_pid") == os.getpid():
        return True

    # Doc didn't match (either missing entirely, or lease held & fresh).
    # Try to insert if missing.
    try:
        coll.insert_one({
            "_id": key,
            "in_progress": True,
            "lease_at_ms": now_ms,
            "lease_pid": os.getpid(),
        })
        return True
    except DuplicateKeyError:
        # Doc exists but lease is held and fresh — another process owns it.
        return False


def get_last_watermark(spec: CollectionSpec) -> int | None:
    """Return the last successful ``release_time_ms`` watermark for this spec.

    Used by the auto-sync loop to cap each poll to docs newer than the last
    successful cycle (``ingest_collection(since_ms=...)``). Returns ``None``
    if we've never run a successful cycle for this spec — the caller should
    treat that as "ingest from the beginning" (subject to its own ``limit``).
    """
    doc = _load_sync_state_doc(spec)
    if not doc:
        return None
    wm = doc.get("last_release_time_ms")
    try:
        return int(wm) if wm is not None else None
    except (TypeError, ValueError):
        return None


def get_last_watermark_str(spec: CollectionSpec) -> str | None:
    """Return the last successful ``release_time`` *string* watermark.

    Five specs don't have an epoch-ms field (``alphapai/*`` and
    ``jinmen/meetings``). For those, ``ingest_collection`` can take a
    ``since_str`` argument and filter in Mongo via ``{date_str_field:
    {"$gt": since_str}}``, which relies on the canonical
    ``YYYY-MM-DD HH:MM[:SS]`` format being lexicographically sortable.
    """
    doc = _load_sync_state_doc(spec)
    if not doc:
        return None
    wm = doc.get("last_release_time_str")
    if wm is None:
        return None
    wm = str(wm).strip()
    return wm or None


def get_last_pdf_watermark(spec: CollectionSpec) -> int | None:
    """Return the last ``pdf_text_extracted_at`` epoch-ms watermark.

    Closes the back-fill gap: the parser writes ``pdf_text_md`` +
    ``pdf_text_extracted_at`` onto docs whose ``release_time_ms`` is
    months old, which the date-watermark cursor never re-reads. The auto-
    sync loop ORs this watermark with the date-watermark for ``has_pdf``
    specs so freshly-parsed docs flow into Milvus within one cycle.
    """
    if not spec.has_pdf:
        return None
    doc = _load_sync_state_doc(spec)
    if not doc:
        return None
    wm = doc.get("last_pdf_extracted_ms")
    try:
        return int(wm) if wm is not None else None
    except (TypeError, ValueError):
        return None


def _load_sync_state_doc(spec: CollectionSpec) -> dict | None:
    try:
        return _state_client()[SYNC_STATE_DB]["vector_sync_state"].find_one(
            {"_id": _sync_state_key(spec)},
        )
    except Exception as e:
        logger.debug("sync state read %s failed: %s", _sync_state_key(spec), e)
        return None


def release_lease(
    mc: MongoClient, spec: CollectionSpec, watermark_ms: int | None = None,
    stats: dict | None = None, watermark_str: str | None = None,
    pdf_watermark_ms: int | None = None,
) -> None:
    """Release the lease; optionally bump the watermark + record run stats.

    Supports both epoch-ms and string watermarks — five specs (alphapai/*,
    jinmen/meetings) sort by ``publish_time``/``release_time`` strings, not
    ms, so the caller may set ``watermark_str`` instead of ``watermark_ms``.

    ``pdf_watermark_ms`` (only meaningful for ``has_pdf=True`` specs) tracks
    the high-water mark of ``pdf_text_extracted_at`` seen this cycle so the
    next poll can OR-filter for fresh PDF parses on otherwise-old docs.
    """
    update: dict[str, Any] = {
        "in_progress": False,
        "last_run_at_ms": int(time.time() * 1000),
    }
    if watermark_ms is not None:
        update["last_release_time_ms"] = watermark_ms
    if watermark_str is not None:
        update["last_release_time_str"] = watermark_str
    if pdf_watermark_ms is not None:
        update["last_pdf_extracted_ms"] = pdf_watermark_ms
    if stats is not None:
        update["last_run_stats"] = stats
    try:
        _state_client()[SYNC_STATE_DB]["vector_sync_state"].update_one(
            {"_id": _sync_state_key(spec)},
            {"$set": update},
            upsert=True,
        )
    except Exception as e:
        logger.warning("release_lease failed: %s", e)


# ── Embed + upsert (async path; wraps pymilvus sync calls in to_thread) ──


async def _embed_and_upsert_batch(
    rows: list[dict],
    mv: MilvusClient,
    collection: str,
    *,
    max_retries: int = 2,
    retry_delay_s: float = 30.0,
) -> int:
    """One batch: embed via TEI → attach vectors → upsert Milvus.
    Retries on transient errors. Non-zero return is rows actually upserted.
    """
    if not rows:
        return 0
    texts = [r["chunk_text"] for r in rows]
    attempt = 0
    while True:
        try:
            vecs = await tei_client.embed_batch(texts)
            for r, v in zip(rows, vecs):
                r["dense_vector"] = v
            await asyncio.to_thread(mv.upsert, collection_name=collection, data=rows)
            return len(rows)
        except tei_client.TEICircuitOpen as e:
            attempt += 1
            if attempt > max_retries:
                logger.error("TEI circuit open — dropping batch of %d after retries", len(rows))
                raise
            logger.warning("TEI circuit open, retry %d/%d in %.0fs",
                           attempt, max_retries, retry_delay_s)
            await asyncio.sleep(retry_delay_s)
        except (tei_client.TEIError, Exception) as e:
            attempt += 1
            if attempt > max_retries:
                logger.error("batch failed after %d attempts: %s", max_retries, e)
                raise
            logger.warning("batch attempt %d/%d failed: %s; retrying", attempt, max_retries, e)
            await asyncio.sleep(retry_delay_s)


# ── Main ingest driver ────────────────────────────────────────────


async def ingest_collection(
    spec: CollectionSpec,
    *,
    limit: int | None = None,
    since_ms: int | None = None,
    since_str: str | None = None,
    since_pdf_ms: int | None = None,
    force: bool = False,
    batch_size: int = 32,
    use_lease: bool = True,
    progress_interval_s: float = 60.0,
) -> dict[str, int]:
    """Ingest every doc in one Mongo collection into Milvus.

    Consistency guarantees
    ----------------------
    • **Adds**: new docs → new chunks upserted.
    • **Updates**: when a doc's text changes, produces new chunk_ids; old
      chunks for that doc that are NOT in the new set are deleted (closes the
      update-orphan bug).
    • **Skipped**: if every new chunk_id already exists in Milvus with the
      current embedding_model_version, the doc is skipped (no embed cost).
    • **Deletes**: NOT handled here — use ``sweep_deleted_docs`` or
      ``delete_doc`` directly.

    Failure isolation
    -----------------
    A single malformed doc is logged and skipped, not fatal. A batch that
    fails embedding or upsert is retried twice with 30 s backoff, then
    logged to the dead-letter queue (future) and skipped.

    Parameters
    ----------
    since_ms : only fetch docs with release_time_ms > this (watermark polling).
    force    : re-embed even if the chunk_id already exists with current model version.
    limit    : cap docs processed (for testing).
    batch_size : embed/upsert batch size.
    use_lease : acquire Mongo lease in admin.vector_sync_state to prevent
                overlapping pollers from double-processing.
    progress_interval_s : log progress every N seconds (and on every 500 chunks).
    """
    s = get_settings()
    model_version = s.embedding_model_version
    mc = MongoClient(s.alphapai_mongo_uri, serverSelectionTimeoutMS=5000)
    mv = MilvusClient(uri=f"http://{s.milvus_host}:{s.milvus_port}")
    coll = mc[mongo_db_name_for(spec)][spec.collection]
    key = _sync_state_key(spec)
    milvus_coll = s.effective_milvus_collection

    # ── Lease ─────────────────────────────────────────────────
    if use_lease:
        if not await asyncio.to_thread(acquire_lease, mc, spec):
            logger.warning("ingest %s SKIPPED — another process holds lease", key)
            return {"skipped_due_to_lease": 1, "elapsed_s": 0,
                    "docs_seen": 0, "docs_chunked": 0, "docs_unchanged": 0,
                    "docs_errored": 0, "chunks_upserted": 0, "chunks_deleted": 0}

    # ── Build Mongo query ─────────────────────────────────────
    # Exclude crawler-internal docs: legacy `crawler_*`/`daily_*` checkpoints
    # from the pre-migration local Mongo, plus the remote Mongo's `_state`,
    # `_probe`, `account`, `test` meta docs.
    query: dict[str, Any] = {
        "_id": {"$not": {"$regex": r"^(crawler_|daily_|_probe$|_state$|account$|test$)"}},
    }
    # Build watermark clauses. For has_pdf specs we OR the date-watermark with
    # a separate pdf_text_extracted_at watermark — old docs that just got their
    # PDF parsed (release_time_ms unchanged) must still flow through ingest.
    clauses: list[dict[str, Any]] = []
    if since_ms and spec.date_ms_field:
        clauses.append({spec.date_ms_field: {"$gt": since_ms}})
    elif since_str and spec.date_str_field:
        # String watermark path (specs without epoch-ms). Relies on the
        # canonical `YYYY-MM-DD HH:MM[:SS]` format crawlers produce being
        # lexicographically sortable — verified for alphapai's publish_time
        # and jinmen meetings' release_time.
        clauses.append({spec.date_str_field: {"$gt": since_str}})
    if spec.has_pdf and since_pdf_ms is not None:
        # `since_pdf_ms == 0` is meaningful — it means "first cycle, catch
        # every PDF-back-filled doc whose pdf_text_extracted_at is set." Treat
        # as a sentinel rather than the falsy "skip this clause" value.
        from datetime import datetime as _dt, timezone as _tz
        pdf_dt = _dt.fromtimestamp(since_pdf_ms / 1000.0, tz=_tz.utc)
        clauses.append({"pdf_text_extracted_at": {"$gt": pdf_dt}})
    if len(clauses) == 1:
        query.update(clauses[0])
    elif len(clauses) > 1:
        query["$or"] = clauses

    projection: dict[str, int] = {
        "_id": 1,
        spec.title_field: 1,
        "_canonical_tickers": 1,
    }
    for f in spec.text_fields:
        projection[f] = 1
    if spec.date_str_field:
        projection[spec.date_str_field] = 1
    if spec.date_ms_field:
        projection[spec.date_ms_field] = 1
    if spec.institution_field:
        projection[spec.institution_field] = 1
    if spec.url_field:
        projection[spec.url_field] = 1
    if spec.ticker_fallback_path == "stocks":
        projection["stocks"] = 1
    if spec.ticker_fallback_path == "companies":
        projection["companies"] = 1
    if spec.has_pdf:
        # Needed to advance the pdf-watermark per doc, regardless of whether
        # this doc's text content actually changed this cycle.
        projection["pdf_text_extracted_at"] = 1

    sort_field = spec.date_ms_field or spec.date_str_field
    cursor = coll.find(query, projection=projection)
    if sort_field:
        cursor = cursor.sort([(sort_field, 1)])  # oldest first so watermark bump is accurate
    if limit:
        cursor = cursor.limit(limit)

    # ── Prefetch existing chunks into memory (avoids per-doc Milvus RPC) ──
    # Sync Milvus query — wrap so the multi-second paginated load doesn't pin
    # the event loop on collections with tens of thousands of chunks.
    existing_by_doc = await asyncio.to_thread(
        _prefetch_existing_by_doc, mv, milvus_coll, spec.db, spec.collection,
    )

    # ── Counters ──────────────────────────────────────────────
    docs_seen = 0
    docs_chunked = 0
    docs_unchanged = 0
    docs_errored = 0
    chunks_upserted = 0
    chunks_deleted = 0
    max_release_ms = since_ms or 0
    max_release_str = since_str or ""
    max_pdf_extracted_ms = since_pdf_ms or 0
    chunks_pending: list[dict] = []
    t0 = time.monotonic()
    last_log = t0
    last_log_chunks = 0

    def _log_progress(*, force_log: bool = False) -> None:
        nonlocal last_log, last_log_chunks
        now = time.monotonic()
        due_time = (now - last_log) >= progress_interval_s
        due_count = (chunks_upserted - last_log_chunks) >= 500
        if not (force_log or due_time or due_count):
            return
        elapsed = now - t0
        rate = chunks_upserted / elapsed if elapsed > 0 else 0.0
        logger.info(
            "ingest %s progress: docs_seen=%d chunked=%d unchanged=%d errored=%d "
            "chunks_upserted=%d chunks_deleted=%d elapsed=%.0fs rate=%.1f chunks/s",
            key, docs_seen, docs_chunked, docs_unchanged, docs_errored,
            chunks_upserted, chunks_deleted, elapsed, rate,
        )
        last_log = now
        last_log_chunks = chunks_upserted

    async def flush() -> None:
        nonlocal chunks_pending, chunks_upserted
        if not chunks_pending:
            return
        try:
            for start in range(0, len(chunks_pending), batch_size):
                batch = chunks_pending[start:start + batch_size]
                n = await _embed_and_upsert_batch(
                    batch, mv, milvus_coll, max_retries=2, retry_delay_s=30.0,
                )
                chunks_upserted += n
                _log_progress()
        except Exception as e:
            logger.error("flush failed after retries — dropping %d chunks: %s",
                         len(chunks_pending), e)
        chunks_pending = []

    # ── Main loop ─────────────────────────────────────────────
    logger.info("ingest %s start (force=%s, since_ms=%s, since_pdf_ms=%s, limit=%s)",
                key, force, since_ms, since_pdf_ms, limit)

    try:
        async for doc in _aiter_cursor(cursor, batch_size=200):
            docs_seen += 1
            doc_id = ""
            try:
                # Per-doc work (markdown chunking, hashing, language detect) is
                # CPU-bound sync that can run hundreds of ms on big PDFs. Off-
                # loading to a thread keeps the event loop free for unrelated
                # FastAPI handlers (e.g. the workbench's sentimentrader cards)
                # that would otherwise stall behind ingest cycles.
                rows = await asyncio.to_thread(build_rows_for_doc, spec, doc)
                if not rows:
                    continue
                doc_id = rows[0]["doc_id"]
                new_chunk_ids = {r["chunk_id"] for r in rows}

                # Always bump watermark once we have built the rows — the doc
                # has been "seen and confirmed" whether or not anything changes.
                # Next poll can skip it via since_ms + release_time_ms filter.
                # Cursor is sorted ascending so this climbs monotonically.
                rms = int(rows[0].get("release_time_ms") or 0)
                if rms > max_release_ms:
                    max_release_ms = rms
                # Also track the string watermark when the spec doesn't carry
                # an epoch-ms field — the poller persists either one depending
                # on spec shape so incremental polls advance correctly.
                if spec.date_str_field and not spec.date_ms_field:
                    rstr = str(doc.get(spec.date_str_field) or "")
                    if rstr and rstr > max_release_str:
                        max_release_str = rstr

                # PDF watermark: docs whose pdf_text_extracted_at is fresher
                # than the date-watermark must still flow through next cycle if
                # the parser back-fills more docs after this run. The cursor
                # isn't ordered on this field, so the bump is "max-of-seen".
                if spec.has_pdf:
                    pdf_ts = doc.get("pdf_text_extracted_at")
                    if pdf_ts is not None:
                        try:
                            pdf_ms = int(pdf_ts.timestamp() * 1000)
                            if pdf_ms > max_pdf_extracted_ms:
                                max_pdf_extracted_ms = pdf_ms
                        except (AttributeError, TypeError, ValueError):
                            pass

                # Existing chunks from prefetch (O(1) dict lookup).
                existing = existing_by_doc.get(doc_id, [])
                existing_by_id = {r["chunk_id"]: r for r in existing}

                # Decide skip-if-unchanged.
                if not force and existing_by_id:
                    all_present = new_chunk_ids.issubset(existing_by_id.keys())
                    no_extras = set(existing_by_id.keys()) == new_chunk_ids
                    model_match = all(
                        r.get("embedding_model_version") == model_version
                        for r in existing
                    )
                    if all_present and no_extras and model_match:
                        docs_unchanged += 1
                        _log_progress()
                        continue

                # Delete chunks that exist but are no longer produced (stale updates).
                stale_ids = set(existing_by_id.keys()) - new_chunk_ids
                if stale_ids:
                    n = await asyncio.to_thread(
                        _delete_chunk_ids, mv, milvus_coll, stale_ids,
                    )
                    chunks_deleted += n
                    # Keep the prefetch map in sync so a second run in the
                    # same session would see the delete.
                    existing_by_doc[doc_id] = [
                        r for r in existing if r["chunk_id"] not in stale_ids
                    ]

                # Only embed+upsert chunks that don't already exist with the
                # current model version. (chunk_id is deterministic so equal
                # chunk_id across runs means identical text.)
                if force:
                    to_upsert = rows
                else:
                    to_upsert = []
                    for r in rows:
                        ex = existing_by_id.get(r["chunk_id"])
                        if ex is None:
                            to_upsert.append(r)  # brand new
                        elif ex.get("embedding_model_version") != model_version:
                            to_upsert.append(r)  # model changed → re-embed

                if to_upsert:
                    chunks_pending.extend(to_upsert)
                    docs_chunked += 1

                if len(chunks_pending) >= batch_size * 4:
                    await flush()
            except Exception as e:
                docs_errored += 1
                logger.warning(
                    "doc failed %s id=%s: %s",
                    key, doc.get("_id"), e,
                )
                _log_progress()
                continue

        await flush()
    finally:
        try:
            cursor.close()
        except Exception:
            pass
        # Always release the lease + advance the watermark, even if an
        # exception interrupted the loop. A leaked lease would otherwise
        # block subsequent cycles for the full 2h TTL.
        if use_lease:
            try:
                partial_elapsed = int(time.monotonic() - t0)
                # has_pdf specs always persist a non-None pdf_watermark so the
                # next cycle's OR-clause stays armed. Non-PDF specs persist None.
                pdf_wm_persist = max_pdf_extracted_ms if spec.has_pdf else None
                partial_stats = {
                    "docs_seen": docs_seen,
                    "docs_chunked": docs_chunked,
                    "docs_unchanged": docs_unchanged,
                    "docs_errored": docs_errored,
                    "chunks_upserted": chunks_upserted,
                    "chunks_deleted": chunks_deleted,
                    "elapsed_s": partial_elapsed,
                    "watermark_ms": max_release_ms,
                    "watermark_str": max_release_str or None,
                    "pdf_watermark_ms": pdf_wm_persist,
                }
                await asyncio.to_thread(
                    release_lease,
                    mc, spec,
                    watermark_ms=max_release_ms,
                    watermark_str=max_release_str or None,
                    pdf_watermark_ms=pdf_wm_persist,
                    stats=partial_stats,
                )
            except Exception:
                logger.exception("release_lease failed in finally (lease may leak)")

    elapsed = time.monotonic() - t0
    stats = {
        "docs_seen": docs_seen,
        "docs_chunked": docs_chunked,
        "docs_unchanged": docs_unchanged,
        "docs_errored": docs_errored,
        "chunks_upserted": chunks_upserted,
        "chunks_deleted": chunks_deleted,
        "elapsed_s": int(elapsed),
        "watermark_ms": max_release_ms,
        "watermark_str": max_release_str or None,
        "pdf_watermark_ms": max_pdf_extracted_ms if spec.has_pdf else None,
    }

    _log_progress(force_log=True)
    logger.info("ingest %s DONE: %s", key, stats)
    return stats


# ── Delete sweep (called daily; reconciles Milvus to Mongo) ──


async def sweep_deleted_docs(
    spec: CollectionSpec, *, dry_run: bool = False, use_lease: bool = True,
) -> dict[str, int]:
    """Diff Milvus doc_ids ↔ Mongo _id. Delete Milvus chunks whose Mongo doc
    no longer exists. Designed to run once per day per collection at ~03:00.

    dry_run: compute the diff but do not delete.
    """
    s = get_settings()
    mc = MongoClient(s.alphapai_mongo_uri, serverSelectionTimeoutMS=5000)
    mv = MilvusClient(uri=f"http://{s.milvus_host}:{s.milvus_port}")
    key = _sync_state_key(spec)
    milvus_coll = s.effective_milvus_collection
    t0 = time.monotonic()

    if use_lease and not await asyncio.to_thread(acquire_lease, mc, spec):
        logger.warning("sweep %s SKIPPED — lease held", key)
        return {"skipped_due_to_lease": 1}

    try:
        # Mongo IDs — drain on worker thread so the loop stays responsive over
        # large collections (some have 40k+ docs).
        mongo_cursor = mc[mongo_db_name_for(spec)][spec.collection].find(
            {"_id": {"$not": {"$regex": r"^(crawler_|daily_|_probe$|_state$|account$|test$)"}}},
            projection={"_id": 1},
        )
        mongo_ids: set[str] = set()
        async for d in _aiter_cursor(mongo_cursor, batch_size=500):
            mongo_ids.add(_vector_doc_id(spec.db, spec.collection, d["_id"]))

        # Milvus doc_ids for this collection (paginate by chunk_id ordering).
        # Each mv.query is a sync gRPC call — wrap in to_thread so 16K-row
        # pages don't pin the loop.
        milvus_doc_ids: set[str] = set()
        last_pk = ""
        while True:
            filt = f'db == "{spec.db}" and collection == "{spec.collection}"'
            if last_pk:
                filt += f' and chunk_id > "{last_pk}"'
            try:
                page = await asyncio.to_thread(
                    mv.query,
                    collection_name=milvus_coll,
                    filter=filt,
                    output_fields=["chunk_id", "doc_id"],
                    limit=16384,
                )
            except Exception as e:
                logger.error("sweep query failed: %s", e)
                return {"error": str(e)}
            if not page:
                break
            for r in page:
                milvus_doc_ids.add(r["doc_id"])
            new_last = max(r["chunk_id"] for r in page)
            if new_last == last_pk or len(page) < 16384:
                break
            last_pk = new_last

        tombstones = milvus_doc_ids - mongo_ids
        logger.info(
            "sweep %s: mongo_docs=%d milvus_docs=%d tombstones=%d dry_run=%s",
            key, len(mongo_ids), len(milvus_doc_ids), len(tombstones), dry_run,
        )

        deleted = 0
        if tombstones and not dry_run:
            for did in sorted(tombstones):
                deleted += await asyncio.to_thread(delete_doc, mv, milvus_coll, did)
            # Audit
            try:
                _state_client()[SYNC_STATE_DB]["vector_tombstones"].insert_one({
                    "collection": key,
                    "tombstoned_doc_ids": sorted(tombstones),
                    "count": len(tombstones),
                    "swept_at_ms": int(time.time() * 1000),
                })
            except Exception as e:
                logger.warning("tombstone audit write failed: %s", e)

        elapsed = time.monotonic() - t0
        return {
            "mongo_docs": len(mongo_ids),
            "milvus_docs": len(milvus_doc_ids),
            "tombstones": len(tombstones),
            "deleted": deleted,
            "dry_run": dry_run,
            "elapsed_s": int(elapsed),
        }
    finally:
        if use_lease:
            try:
                await asyncio.to_thread(release_lease, mc, spec)
            except Exception:
                logger.exception("sweep release_lease failed (lease may leak)")


# ── CLI ──────────────────────────────────────────────────────────


def _parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--coll", required=True,
                    help="e.g. alphapai/roadshows. Use 'all' to ingest every spec in SPECS_LIST in order.")
    ap.add_argument("--limit", type=int, help="Cap docs processed per collection")
    ap.add_argument("--since", type=int, help="Ingest docs with release_time_ms > this")
    ap.add_argument("--since-str", type=str, dest="since_str",
                    help="String watermark for specs without release_time_ms (alphapai/*, jinmen/meetings). "
                         "Format must match the crawler field: 'YYYY-MM-DD HH:MM' or '... :SS'.")
    ap.add_argument("--force", action="store_true",
                    help="Re-embed even if chunk_id exists with current model version")
    ap.add_argument("--batch-size", type=int, default=32,
                    help="Embedding batch size (default 32)")
    ap.add_argument("--no-lease", action="store_true",
                    help="Skip Mongo lease (useful for one-off tests; DO NOT use in prod)")
    return ap.parse_args(argv)


async def _main(argv: list[str] | None = None) -> int:
    args = _parse_args(argv)

    if args.coll == "all":
        targets = SPECS_LIST
    elif args.coll in SPECS_BY_KEY:
        targets = [SPECS_BY_KEY[args.coll]]
    else:
        print(f"unknown collection '{args.coll}'. Known: all, " + ", ".join(sorted(SPECS_BY_KEY)),
              file=sys.stderr)
        return 2

    results: list[dict[str, Any]] = []
    try:
        for spec in targets:
            try:
                r = await ingest_collection(
                    spec,
                    limit=args.limit,
                    since_ms=args.since,
                    since_str=args.since_str,
                    force=args.force,
                    batch_size=args.batch_size,
                    use_lease=not args.no_lease,
                )
                r["collection"] = f"{spec.db}/{spec.collection}"
                results.append(r)
            except Exception as e:
                logger.exception("ingest %s/%s crashed: %s", spec.db, spec.collection, e)
                results.append({
                    "collection": f"{spec.db}/{spec.collection}",
                    "crashed": True, "error": str(e),
                })
    finally:
        # Close the shared httpx client on the SAME event loop that created
        # it — doing this at main()-level (after asyncio.run returns) crashes
        # with "Event loop is closed".
        await tei_client.close()

    print()
    print("== ingest summary ==")
    for r in results:
        coll = r.get("collection", "?")
        if r.get("skipped_due_to_lease"):
            print(f"  {coll}: SKIPPED (lease held)")
        elif r.get("crashed"):
            print(f"  {coll}: CRASHED — {r.get('error')}")
        else:
            print(f"  {coll}: seen={r.get('docs_seen',0):>6}  "
                  f"chunked={r.get('docs_chunked',0):>6}  "
                  f"unchanged={r.get('docs_unchanged',0):>6}  "
                  f"errored={r.get('docs_errored',0):>3}  "
                  f"upserted={r.get('chunks_upserted',0):>7}  "
                  f"deleted={r.get('chunks_deleted',0):>5}  "
                  f"elapsed={r.get('elapsed_s',0):>4}s")
    return 0 if all(not r.get("crashed") for r in results) else 1


def main(argv: list[str] | None = None) -> int:
    logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")
    return asyncio.run(_main(argv))


if __name__ == "__main__":
    sys.exit(main())
