"""Stock ticker verification service.

Verifies LLM-generated stock tickers against authoritative stock lists,
falling back to Baidu search + LLM for unknown tickers.

Stock lists:
- A-shares: loaded from CSV (code, name)
- US stocks: loaded from CSV (code, name) — generated by scripts/fetch_stock_lists.py
- HK stocks: loaded from CSV (code, name) — generated by scripts/fetch_stock_lists.py

Verification flow:
1. Parse ticker string (e.g. "贵州茅台(600519.SH)" → name="贵州茅台", code="600519.SH")
2. Search local stock lists by code and name (fuzzy)
3. If found → return corrected name + code
4. If not found → Baidu search "{name} 股票代码" → LLM parse result
5. If Baidu confirms → return verified name + code
6. If Baidu cannot confirm → drop the ticker
"""
from __future__ import annotations

import asyncio
import csv
import json
import logging
import os
import re
from pathlib import Path
from typing import Any

import httpx
from openai import AsyncOpenAI

logger = logging.getLogger(__name__)


def _normalize_name(name: str) -> str:
    """Normalize a stock name: Traditional→Simplified Chinese, full-width→half-width, clean suffixes."""
    try:
        import zhconv
        name = zhconv.convert(name, "zh-cn")
    except ImportError:
        pass
    # Full-width → half-width for common chars (e.g. "－Ｗ" → "-W")
    name = name.translate(str.maketrans(
        "０１２３４５６７８９ＡＢＣＤＥＦＧＨＩＪＫＬＭＮＯＰＱＲＳＴＵＶＷＸＹＺ－",
        "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ-",
    ))
    # Clean common HK suffixes: "-W", "-SW", "-SWR", "-R" (dual-class/weighted voting marks)
    name = re.sub(r"[-](?:SWR|SW|WR|W|R|S)$", "", name).strip()
    return name


def _format_ticker(name: str, code: str) -> str:
    """Format a verified ticker as 'name(code)', handling names that contain parentheses."""
    name = _normalize_name(name)
    # Strip inner parenthesized qualifiers from name (e.g. "西门子(ADR)" → "西门子")
    # to avoid confusing double-parentheses like "西门子(ADR)(SIEGY)"
    name = re.sub(r"\s*\([^)]*\)\s*$", "", name).strip()
    return f"{name}({code})"


def _extract_json(text: str) -> dict | None:
    """Best-effort JSON extraction from LLM output (handles <think> tags, markdown)."""
    text = re.sub(r"<think>.*?</think>", "", text, flags=re.DOTALL).strip()
    text = re.sub(r"<think>.*", "", text, flags=re.DOTALL).strip()
    try:
        return json.loads(text)
    except json.JSONDecodeError:
        pass
    m = re.search(r"```(?:json)?\s*(\{.*?\})\s*```", text, re.DOTALL)
    if m:
        try:
            return json.loads(m.group(1))
        except json.JSONDecodeError:
            pass
    depth = 0
    start = -1
    for i, ch in enumerate(text):
        if ch == '{':
            if depth == 0:
                start = i
            depth += 1
        elif ch == '}':
            depth -= 1
            if depth == 0 and start >= 0:
                try:
                    return json.loads(text[start:i + 1])
                except json.JSONDecodeError:
                    start = -1
    return None

# Default paths for stock list CSVs
_DATA_DIR = Path(__file__).resolve().parent.parent.parent.parent / "data"
_A_SHARE_CSV_NEW = _DATA_DIR / "a_stock_list.csv"
_A_SHARE_CSV_OLD = Path("/home/ygwang/pdf_analyzer/research/stock_list.csv")
_A_SHARE_CSV = _A_SHARE_CSV_NEW if _A_SHARE_CSV_NEW.exists() else _A_SHARE_CSV_OLD
_US_STOCK_CSV = _DATA_DIR / "us_stock_list.csv"
_HK_STOCK_CSV = _DATA_DIR / "hk_stock_list.csv"

# Baidu AI Search API
BAIDU_API_URL = "https://qianfan.baidubce.com/v2/ai_search/web_search"


class StockVerifier:
    """Verify and correct stock tickers using local lists + Baidu search."""

    def __init__(
        self,
        baidu_api_key: str = "",
        llm_client: AsyncOpenAI | None = None,
        llm_model: str = "MiniMax-M2",
    ):
        self.baidu_api_key = baidu_api_key
        self.llm = llm_client
        self.llm_model = llm_model

        # Stock lookup dicts: code→name, name→code
        self._a_code_to_name: dict[str, str] = {}
        self._a_name_to_code: dict[str, str] = {}
        self._us_code_to_name: dict[str, str] = {}
        self._us_name_to_code: dict[str, str] = {}
        self._hk_code_to_name: dict[str, str] = {}
        self._hk_name_to_code: dict[str, str] = {}

        # Portfolio/custom stocks not in standard lists (JP, KR, etc.)
        self._custom_code_to_name: dict[str, str] = {}
        self._custom_name_to_code: dict[str, str] = {}
        self._custom_code_to_market: dict[str, str] = {}  # code → market label (日股, 韩股, etc.)

        # Cache for Baidu search results to avoid repeated queries
        self._search_cache: dict[str, dict | None] = {}

        self._loaded = False

    def load_stock_lists(self) -> None:
        """Load all available stock list CSVs into memory."""
        self._load_a_shares()
        self._load_us_stocks()
        self._load_hk_stocks()
        self._load_portfolio_stocks()
        self._loaded = True
        logger.info(
            "[StockVerifier] Loaded: A-shares=%d, US=%d, HK=%d, custom=%d",
            len(self._a_code_to_name),
            len(self._us_code_to_name),
            len(self._hk_code_to_name),
            len(self._custom_code_to_name),
        )

    def _load_portfolio_stocks(self) -> None:
        """Register stocks from portfolio config that aren't in standard lists.

        This covers Japanese (日股), Korean (韩股), and other non-standard markets
        so they aren't dropped during ticker verification.
        """
        portfolio_yaml = Path(__file__).resolve().parent.parent.parent.parent / "config" / "portfolio_sources.yaml"
        if not portfolio_yaml.exists():
            return
        try:
            import yaml
            with open(portfolio_yaml, "r", encoding="utf-8") as f:
                data = yaml.safe_load(f) or {}
            for s in data.get("sources", []):
                ticker = s.get("stock_ticker", "").strip()
                name = s.get("stock_name", "").strip()
                if not ticker or not name:
                    continue
                # Skip stocks already in standard lists
                if self._lookup_by_code(ticker.upper()):
                    continue
                if name in self._a_name_to_code or name in self._us_name_to_code or name in self._hk_name_to_code:
                    continue
                # Register as custom stock
                market = s.get("stock_market", "")
                self._custom_code_to_name[ticker] = name
                self._custom_code_to_name[ticker.upper()] = name
                self._custom_name_to_code[name] = ticker
                self._custom_code_to_market[ticker] = market
                self._custom_code_to_market[ticker.upper()] = market
            if self._custom_code_to_name:
                logger.info(
                    "[StockVerifier] Registered %d custom portfolio stocks: %s",
                    len(self._custom_name_to_code),
                    ", ".join(f"{n}({c})" for n, c in self._custom_name_to_code.items()),
                )
        except Exception as e:
            logger.warning("[StockVerifier] Failed to load portfolio stocks: %s", e)

    def _load_a_shares(self) -> None:
        """Load A-share stock list from CSV. Format: 代码,名称"""
        if not _A_SHARE_CSV.exists():
            logger.warning("[StockVerifier] A-share CSV not found: %s", _A_SHARE_CSV)
            return
        with open(_A_SHARE_CSV, "r", encoding="utf-8-sig") as f:
            reader = csv.DictReader(f)
            for row in reader:
                code_raw = row.get("代码", row.get("\ufeff代码", "")).strip()
                name = row.get("名称", "").strip()
                if not code_raw or not name:
                    continue
                # Pad code to 6 digits
                code_raw = code_raw.zfill(6)
                # Determine exchange suffix
                if code_raw.startswith(("6",)):
                    full_code = f"{code_raw}.SH"
                elif code_raw.startswith(("0", "3")):
                    full_code = f"{code_raw}.SZ"
                elif code_raw.startswith(("8", "4")):
                    full_code = f"{code_raw}.BJ"
                else:
                    full_code = code_raw
                self._a_code_to_name[full_code] = name
                self._a_code_to_name[code_raw] = name  # Also store without suffix
                self._a_name_to_code[name] = full_code

    def _load_us_stocks(self) -> None:
        """Load US stock list from CSV. Format: code,name"""
        if not _US_STOCK_CSV.exists():
            logger.info("[StockVerifier] US stock CSV not found: %s (will use Baidu fallback)", _US_STOCK_CSV)
            return
        with open(_US_STOCK_CSV, "r", encoding="utf-8") as f:
            reader = csv.DictReader(f)
            for row in reader:
                code = row.get("code", "").strip()
                name = row.get("name", "").strip()
                if not code or not name:
                    continue
                # Store both full code (105.AAPL) and short code (AAPL)
                self._us_code_to_name[code] = name
                short_code = code.split(".")[-1] if "." in code else code
                self._us_code_to_name[short_code] = name
                self._us_name_to_code[name] = short_code

    def _load_hk_stocks(self) -> None:
        """Load HK stock list from CSV. Format: code,name"""
        if not _HK_STOCK_CSV.exists():
            logger.info("[StockVerifier] HK stock CSV not found: %s (will use Baidu fallback)", _HK_STOCK_CSV)
            return
        with open(_HK_STOCK_CSV, "r", encoding="utf-8") as f:
            reader = csv.DictReader(f)
            for row in reader:
                code = row.get("code", "").strip()
                name = row.get("name", "").strip()
                if not code or not name:
                    continue
                # Store with .HK suffix too
                self._hk_code_to_name[code] = name
                hk_code = f"{code}.HK" if not code.endswith(".HK") else code
                self._hk_code_to_name[hk_code] = name
                self._hk_name_to_code[name] = code

    # ------------------------------------------------------------------ #
    # Local list lookup
    # ------------------------------------------------------------------ #
    def _lookup_by_code(self, code: str) -> tuple[str, str] | None:
        """Look up stock by code in all lists. Returns (name, full_code) or None."""
        code = code.strip().upper()
        # A-shares
        if code in self._a_code_to_name:
            name = self._a_code_to_name[code]
            # Ensure full code with suffix
            if "." not in code:
                full_code = self._a_name_to_code.get(name, code)
            else:
                full_code = code
            return name, full_code
        # US stocks
        if code in self._us_code_to_name:
            return self._us_code_to_name[code], code
        # HK stocks — also try zero-padded code (LLM may output 0700.HK vs 00700.HK)
        if code in self._hk_code_to_name:
            return self._hk_code_to_name[code], code
        # Try padding numeric part to 5 digits for HK codes (e.g. "700" → "00700", "9888.HK" → "09888.HK")
        if code.endswith(".HK"):
            num_part = code[:-3]
            padded = f"{num_part.zfill(5)}.HK"
            if padded in self._hk_code_to_name:
                return self._hk_code_to_name[padded], padded
        elif re.match(r"^\d{1,4}$", code):
            padded = code.zfill(5)
            if padded in self._hk_code_to_name:
                return self._hk_code_to_name[padded], padded
        # Custom/portfolio stocks (JP, KR, etc.)
        if code in self._custom_code_to_name:
            return self._custom_code_to_name[code], code
        return None

    def _lookup_by_name(self, name: str) -> tuple[str, str] | None:
        """Look up stock by name in all lists. Returns (canonical_name, code) or None."""
        name = name.strip()
        # Exact match first
        if name in self._a_name_to_code:
            return name, self._a_name_to_code[name]
        if name in self._us_name_to_code:
            return name, self._us_name_to_code[name]
        if name in self._hk_name_to_code:
            return name, self._hk_name_to_code[name]
        if name in self._custom_name_to_code:
            return name, self._custom_name_to_code[name]

        # Fuzzy: check if name is a substring of any stock name or vice versa
        # Only for names >= 2 chars to avoid false matches
        if len(name) >= 2:
            for stock_name, stock_code in self._a_name_to_code.items():
                if name in stock_name or stock_name in name:
                    return stock_name, stock_code
            for stock_name, stock_code in self._us_name_to_code.items():
                if name in stock_name or stock_name in name:
                    return stock_name, stock_code
            for stock_name, stock_code in self._hk_name_to_code.items():
                if name in stock_name or stock_name in name:
                    return stock_name, stock_code
            for stock_name, stock_code in self._custom_name_to_code.items():
                if name in stock_name or stock_name in name:
                    return stock_name, stock_code
        return None

    # ------------------------------------------------------------------ #
    # Parse ticker string
    # ------------------------------------------------------------------ #
    @staticmethod
    def _parse_ticker(ticker_str: str) -> tuple[str, str]:
        """Parse a ticker string like '贵州茅台(600519.SH)' into (name, code).

        Also handles: '600519.SH', 'AAPL', '贵州茅台', '0700.HK'.
        """
        ticker_str = ticker_str.strip()
        # Pattern: name(code)
        m = re.match(r"^(.+?)\(([^)]+)\)$", ticker_str)
        if m:
            return m.group(1).strip(), m.group(2).strip()

        # Pure code patterns
        if re.match(r"^\d{6}\.(SH|SZ|BJ)$", ticker_str, re.IGNORECASE):
            return "", ticker_str.upper()
        if re.match(r"^\d{4,5}\.HK$", ticker_str, re.IGNORECASE):
            return "", ticker_str.upper()
        if re.match(r"^[A-Z]{1,5}$", ticker_str):
            return "", ticker_str
        if re.match(r"^\d{6}$", ticker_str):
            return "", ticker_str
        if re.match(r"^\d{5}$", ticker_str):
            return "", ticker_str
        # Mixed alphanumeric codes (e.g. "285A" for JP stocks, "000660" for KR)
        if re.match(r"^[A-Z0-9]{2,6}$", ticker_str, re.IGNORECASE):
            return "", ticker_str.upper()

        # Assume it's a name
        return ticker_str, ""

    # ------------------------------------------------------------------ #
    # Baidu search fallback
    # ------------------------------------------------------------------ #
    async def _baidu_search_stock(self, query: str) -> list[dict]:
        """Search Baidu for stock information."""
        if not self.baidu_api_key:
            return []
        headers = {
            "X-Appbuilder-Authorization": f"Bearer {self.baidu_api_key}",
            "Content-Type": "application/json",
        }
        payload = {
            "messages": [{"content": query, "role": "user"}],
            "search_source": "baidu_search_v2",
            "resource_type_filter": [{"type": "web", "top_k": 5}],
        }
        try:
            async with httpx.AsyncClient(timeout=20, trust_env=False) as client:
                resp = await client.post(BAIDU_API_URL, json=payload, headers=headers)
                resp.raise_for_status()
                data = resp.json()
            references = data.get("references", [])
            results = []
            for ref in references:
                if ref.get("type") != "web":
                    continue
                results.append({
                    "title": ref.get("title", ""),
                    "content": ref.get("content", "")[:1000],
                })
            return results
        except Exception as e:
            logger.warning("[StockVerifier] Baidu search failed for '%s': %s", query, e)
            return []

    async def _llm_verify_stock(self, name: str, code: str, search_results: list[dict]) -> dict | None:
        """Use LLM to determine the correct stock name and code from search results.

        Returns: {"name": str, "code": str} or None if stock doesn't exist.
        """
        if not self.llm or not search_results:
            return None

        search_text = "\n".join(
            f"[{i+1}] {r['title']}\n{r['content']}"
            for i, r in enumerate(search_results[:5])
        )

        prompt = f"""根据以下百度搜索结果，确认这只股票是否真实存在，并返回准确的股票名称和代码。

查询的股票信息：
- 名称: {name or '未知'}
- 代码: {code or '未知'}

搜索结果:
{search_text}

请以JSON格式回答:
{{"exists": true或false, "name": "准确的股票全称", "code": "准确的股票代码(A股如600519.SH，美股如AAPL，港股如00700.HK)"}}

重要规则：
- 核心任务：确认这家公司是否真的是上市公司，如果是，返回正确的名称和代码
- 如果查询的代码有误但搜索结果显示该公司以不同代码上市，返回exists=true并使用搜索结果中的正确代码
- 如果搜索结果中完全找不到相关上市公司信息，exists设为false
- A股代码格式必须是6位数字+.SH/.SZ/.BJ
- 港股代码格式必须是5位数字+.HK（如00700.HK）
- 美股代码是字母缩写如AAPL、NVDA
- name必须是股票的完整中文名称（A股/港股）或英文名称（美股）
- 不要编造信息，只根据搜索结果判断"""

        try:
            resp = await self.llm.chat.completions.create(
                model=self.llm_model,
                messages=[
                    {"role": "system", "content": "你是股票信息验证助手。只根据提供的搜索结果判断股票信息，不要编造。输出严格JSON格式。"},
                    {"role": "user", "content": prompt},
                ],
                max_tokens=300,
                temperature=0.0,
                response_format={"type": "json_object"},
            )
            raw = resp.choices[0].message.content or ""
            parsed = _extract_json(raw)
            if parsed and parsed.get("exists") and parsed.get("name") and parsed.get("code"):
                return {"name": parsed["name"], "code": parsed["code"]}
        except Exception as e:
            logger.warning("[StockVerifier] LLM verify failed: %s", e)
        return None

    # ------------------------------------------------------------------ #
    # Main verification entry point
    # ------------------------------------------------------------------ #
    async def verify_ticker(self, ticker_str: str) -> str | None:
        """Verify a single ticker string and return corrected version.

        Returns: "名称(代码)" format string, or None if ticker is invalid.
        """
        if not self._loaded:
            self.load_stock_lists()

        name, code = self._parse_ticker(ticker_str)

        # Step 1: Try local lookup by code
        if code:
            result = self._lookup_by_code(code)
            if result:
                return _format_ticker(result[0], result[1])

        # Step 2: Try local lookup by name
        if name:
            result = self._lookup_by_name(name)
            if result:
                return _format_ticker(result[0], result[1])

        # Step 3: Baidu search fallback
        cache_key = f"{name}|{code}"
        if cache_key in self._search_cache:
            cached = self._search_cache[cache_key]
            if cached:
                return _format_ticker(cached['name'], cached['code'])
            return None

        search_query = f"{name or code} 股票代码 上市公司"
        # Small delay to avoid Baidu API rate limiting in batch mode
        await asyncio.sleep(0.5)
        search_results = await self._baidu_search_stock(search_query)

        if search_results:
            verified = await self._llm_verify_stock(name, code, search_results)
            if verified:
                self._search_cache[cache_key] = verified
                logger.info(
                    "[StockVerifier] Baidu verified: '%s' → %s(%s)",
                    ticker_str, verified["name"], verified["code"],
                )
                return _format_ticker(verified['name'], verified['code'])
            # LLM said doesn't exist — cache negative result
            self._search_cache[cache_key] = None
        else:
            # Baidu returned no results (could be rate limited) — do NOT cache
            pass

        logger.warning("[StockVerifier] Could not verify ticker: '%s'", ticker_str)
        return None

    async def verify_tickers(self, tickers: list[str]) -> list[str]:
        """Verify a list of ticker strings. Returns list of corrected tickers.

        Invalid/unverifiable tickers are dropped.
        """
        if not tickers:
            return []

        # Process in parallel with concurrency limit
        sem = asyncio.Semaphore(3)  # Limit concurrent Baidu searches

        async def _verify(t: str) -> str | None:
            name, code = self._parse_ticker(t)
            # Quick local check first (no semaphore needed)
            if not self._loaded:
                self.load_stock_lists()
            if code:
                result = self._lookup_by_code(code)
                if result:
                    return _format_ticker(result[0], result[1])
            if name:
                result = self._lookup_by_name(name)
                if result:
                    return _format_ticker(result[0], result[1])
            # Need Baidu search — use semaphore
            async with sem:
                return await self.verify_ticker(t)

        results = await asyncio.gather(*[_verify(t) for t in tickers], return_exceptions=True)
        verified = []
        for i, r in enumerate(results):
            if isinstance(r, str):
                verified.append(r)
            elif isinstance(r, Exception):
                logger.warning("[StockVerifier] Error verifying '%s': %s", tickers[i], r)
        return verified

    async def verify_news_tickers(
        self,
        tickers: list[str],
        stock_hints: list[dict] | None = None,
    ) -> list[str]:
        """Verify tickers from news analysis (format: just codes like '688256', 'NVDA').

        Returns list in '名称(代码)' format for better readability.
        E.g. ['宁德时代(300750.SZ)', 'Apple(AAPL)']

        Args:
            tickers: List of raw ticker codes from LLM extraction.
            stock_hints: Optional list of {"name": ..., "ticker": ...} dicts from LLM,
                         used as fallback when verification cannot find the stock.
        """
        if not tickers:
            return []
        if not self._loaded:
            self.load_stock_lists()

        # Build hint map: ticker_code -> LLM-provided name
        hint_map: dict[str, str] = {}
        if stock_hints:
            for s in stock_hints:
                t = s.get("ticker", "").strip()
                n = s.get("name", "").strip()
                if t and n:
                    hint_map[t] = n

        verified = []
        for t in tickers:
            t = t.strip()
            if not t:
                continue
            try:
                # Try local lookup by code
                result = self._lookup_by_code(t)
                if result:
                    verified.append(_format_ticker(result[0], result[1]))
                    continue
                # For news tickers, also try name lookup
                result = self._lookup_by_name(t)
                if result:
                    verified.append(_format_ticker(result[0], result[1]))
                    continue
                # Baidu fallback — verify_ticker already returns name(code) format
                v = await self.verify_ticker(t)
                if v:
                    verified.append(v)
                    continue
                # Verification failed — use LLM hint name as fallback
                hint_name = hint_map.get(t, "")
                if hint_name and hint_name != t:
                    verified.append(_format_ticker(hint_name, t))
                else:
                    logger.warning(
                        "[StockVerifier] No verification and no hint for '%s' — dropping", t,
                    )
            except Exception as e:
                logger.warning("[StockVerifier] Error verifying '%s': %s", t, e)
                # On error, still try to produce a formatted result from hints
                hint_name = hint_map.get(t, "")
                if hint_name and hint_name != t:
                    verified.append(_format_ticker(hint_name, t))
        return verified


# ------------------------------------------------------------------ #
# Module-level singleton (lazy init)
# ------------------------------------------------------------------ #
_instance: StockVerifier | None = None


def get_stock_verifier(
    baidu_api_key: str = "",
    llm_client: AsyncOpenAI | None = None,
    llm_model: str = "MiniMax-M2",
) -> StockVerifier:
    """Get or create the global StockVerifier singleton."""
    global _instance
    if _instance is None:
        _instance = StockVerifier(
            baidu_api_key=baidu_api_key,
            llm_client=llm_client,
            llm_model=llm_model,
        )
        _instance.load_stock_lists()
    else:
        # Update credentials if provided
        if baidu_api_key:
            _instance.baidu_api_key = baidu_api_key
        if llm_client:
            _instance.llm = llm_client
            _instance.llm_model = llm_model
    return _instance
