"""add alphapai tables

Revision ID: 5ddf6f55ba47
Revises: 92d81a4ce161
Create Date: 2026-03-10 19:57:55.194660
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5ddf6f55ba47'
down_revision: Union[str, None] = '92d81a4ce161'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alphapai_articles',
    sa.Column('arc_code', sa.String(length=100), nullable=False),
    sa.Column('arc_name', sa.Text(), nullable=False),
    sa.Column('author', sa.String(length=200), nullable=True),
    sa.Column('publish_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('spider_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('text_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('read_duration', sa.String(length=20), server_default='', nullable=False),
    sa.Column('is_original', sa.Integer(), server_default='0', nullable=False),
    sa.Column('url', sa.Text(), server_default='', nullable=False),
    sa.Column('content_html_path', sa.Text(), server_default='', nullable=False),
    sa.Column('content_cached', sa.Text(), server_default='', nullable=False),
    sa.Column('wxacc_code', sa.String(length=100), nullable=True),
    sa.Column('research_type', sa.Integer(), nullable=True),
    sa.Column('enrichment', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('is_enriched', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('arc_code')
    )
    op.create_index('ix_ap_art_enriched', 'alphapai_articles', ['is_enriched'], unique=False)
    op.create_index('ix_ap_art_publish', 'alphapai_articles', ['publish_time'], unique=False)
    op.create_table('alphapai_comments',
    sa.Column('cmnt_hcode', sa.String(length=100), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), server_default='', nullable=False),
    sa.Column('psn_name', sa.String(length=200), nullable=True),
    sa.Column('team_cname', sa.String(length=200), nullable=True),
    sa.Column('inst_cname', sa.String(length=200), nullable=True),
    sa.Column('cmnt_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_new_fortune', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('src_type', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.String(length=100), nullable=True),
    sa.Column('enrichment', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('is_enriched', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('cmnt_hcode')
    )
    op.create_index('ix_ap_cmt_date', 'alphapai_comments', ['cmnt_date'], unique=False)
    op.create_index('ix_ap_cmt_enriched', 'alphapai_comments', ['is_enriched'], unique=False)
    op.create_index('ix_ap_cmt_inst', 'alphapai_comments', ['inst_cname'], unique=False)
    op.create_table('alphapai_digests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('digest_date', sa.Date(), nullable=False),
    sa.Column('content_markdown', sa.Text(), server_default='', nullable=False),
    sa.Column('stats', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('model_used', sa.String(length=100), server_default='', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('digest_date')
    )
    op.create_table('alphapai_roadshows_cn',
    sa.Column('trans_id', sa.String(length=100), nullable=False),
    sa.Column('roadshow_id', sa.String(length=100), nullable=False),
    sa.Column('show_title', sa.Text(), nullable=False),
    sa.Column('company', sa.String(length=200), nullable=True),
    sa.Column('guest', sa.Text(), nullable=True),
    sa.Column('stime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('word_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('est_reading_time', sa.String(length=20), server_default='', nullable=False),
    sa.Column('ind_json', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('trans_source', sa.String(length=10), nullable=False),
    sa.Column('content_path', sa.Text(), server_default='', nullable=False),
    sa.Column('content_cached', sa.Text(), server_default='', nullable=False),
    sa.Column('is_conference', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_investigation', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_executive', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_buyside', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('enrichment', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('is_enriched', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('trans_id')
    )
    op.create_index('ix_ap_rs_cn_company', 'alphapai_roadshows_cn', ['company'], unique=False)
    op.create_index('ix_ap_rs_cn_enriched', 'alphapai_roadshows_cn', ['is_enriched'], unique=False)
    op.create_index('ix_ap_rs_cn_roadshow', 'alphapai_roadshows_cn', ['roadshow_id'], unique=False)
    op.create_index('ix_ap_rs_cn_stime', 'alphapai_roadshows_cn', ['stime'], unique=False)
    op.create_table('alphapai_roadshows_us',
    sa.Column('trans_id', sa.String(length=100), nullable=False),
    sa.Column('roadshow_id', sa.String(length=100), nullable=False),
    sa.Column('show_title', sa.Text(), nullable=False),
    sa.Column('company', sa.String(length=200), nullable=True),
    sa.Column('guest', sa.Text(), nullable=True),
    sa.Column('stime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('word_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('est_reading_time', sa.String(length=20), server_default='', nullable=False),
    sa.Column('ind_json', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('trans_source', sa.String(length=10), nullable=False),
    sa.Column('content_path', sa.Text(), server_default='', nullable=False),
    sa.Column('content_cached', sa.Text(), server_default='', nullable=False),
    sa.Column('rec_source', sa.String(length=100), nullable=True),
    sa.Column('quarter_year', sa.String(length=20), nullable=True),
    sa.Column('files_type', sa.String(length=50), nullable=True),
    sa.Column('ai_auxiliary_json', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('enrichment', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('is_enriched', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('trans_id')
    )
    op.create_index('ix_ap_rs_us_enriched', 'alphapai_roadshows_us', ['is_enriched'], unique=False)
    op.create_index('ix_ap_rs_us_roadshow', 'alphapai_roadshows_us', ['roadshow_id'], unique=False)
    op.create_index('ix_ap_rs_us_stime', 'alphapai_roadshows_us', ['stime'], unique=False)
    op.create_table('alphapai_sync_state',
    sa.Column('api_name', sa.String(length=100), nullable=False),
    sa.Column('last_sync_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_sync_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('total_synced', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('api_name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alphapai_sync_state')
    op.drop_index('ix_ap_rs_us_stime', table_name='alphapai_roadshows_us')
    op.drop_index('ix_ap_rs_us_roadshow', table_name='alphapai_roadshows_us')
    op.drop_index('ix_ap_rs_us_enriched', table_name='alphapai_roadshows_us')
    op.drop_table('alphapai_roadshows_us')
    op.drop_index('ix_ap_rs_cn_stime', table_name='alphapai_roadshows_cn')
    op.drop_index('ix_ap_rs_cn_roadshow', table_name='alphapai_roadshows_cn')
    op.drop_index('ix_ap_rs_cn_enriched', table_name='alphapai_roadshows_cn')
    op.drop_index('ix_ap_rs_cn_company', table_name='alphapai_roadshows_cn')
    op.drop_table('alphapai_roadshows_cn')
    op.drop_table('alphapai_digests')
    op.drop_index('ix_ap_cmt_inst', table_name='alphapai_comments')
    op.drop_index('ix_ap_cmt_enriched', table_name='alphapai_comments')
    op.drop_index('ix_ap_cmt_date', table_name='alphapai_comments')
    op.drop_table('alphapai_comments')
    op.drop_index('ix_ap_art_publish', table_name='alphapai_articles')
    op.drop_index('ix_ap_art_enriched', table_name='alphapai_articles')
    op.drop_table('alphapai_articles')
    # ### end Alembic commands ###
