"""Initial schema

Revision ID: 92d81a4ce161
Revises: 
Create Date: 2026-03-10 14:05:44.534855
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '92d81a4ce161'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news_items',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('source_name', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), server_default='', nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('language', sa.String(length=5), server_default='zh', nullable=False),
    sa.Column('market', sa.String(length=20), server_default='china', nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_news_items_content_hash'), 'news_items', ['content_hash'], unique=True)
    op.create_index(op.f('ix_news_items_fetched_at'), 'news_items', ['fetched_at'], unique=False)
    op.create_index(op.f('ix_news_items_source_name'), 'news_items', ['source_name'], unique=False)
    op.create_table('source_health',
    sa.Column('source_name', sa.String(length=200), nullable=False),
    sa.Column('last_success', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_failure', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), server_default='0', nullable=False),
    sa.Column('total_items_fetched', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_healthy', sa.Boolean(), server_default='true', nullable=False),
    sa.PrimaryKeyConstraint('source_name')
    )
    op.create_table('token_usage',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('stage', sa.String(length=50), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('estimated_prompt', sa.Integer(), server_default='0', nullable=False),
    sa.Column('source_name', sa.String(length=200), server_default='', nullable=False),
    sa.Column('duration_ms', sa.Integer(), server_default='0', nullable=False),
    sa.Column('cost_cny', sa.Float(), server_default='0.0', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_token_usage_stage'), 'token_usage', ['stage'], unique=False)
    op.create_index(op.f('ix_token_usage_timestamp'), 'token_usage', ['timestamp'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('role', sa.String(length=20), server_default='trader', nullable=False),
    sa.Column('language', sa.String(length=5), server_default='zh', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('alert_rules',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('rule_type', sa.String(length=50), nullable=False),
    sa.Column('conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('channels', postgresql.JSONB(astext_type=sa.Text()), server_default='["browser"]', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('analysis_results',
    sa.Column('news_item_id', sa.Text(), nullable=False),
    sa.Column('sentiment', sa.String(length=20), server_default='neutral', nullable=False),
    sa.Column('impact_magnitude', sa.String(length=20), server_default='low', nullable=False),
    sa.Column('impact_timeframe', sa.String(length=20), server_default='short_term', nullable=False),
    sa.Column('affected_tickers', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('affected_sectors', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('category', sa.String(length=50), server_default='other', nullable=False),
    sa.Column('summary', sa.Text(), server_default='', nullable=False),
    sa.Column('key_facts', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('bull_case', sa.Text(), server_default='', nullable=False),
    sa.Column('bear_case', sa.Text(), server_default='', nullable=False),
    sa.Column('requires_deep_research', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('research_questions', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('analyzed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('model_used', sa.String(length=100), server_default='', nullable=False),
    sa.Column('surprise_factor', sa.Float(), server_default='0.5', nullable=False),
    sa.Column('is_routine', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('market_expectation', sa.Text(), server_default='', nullable=False),
    sa.Column('quantified_evidence', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.ForeignKeyConstraint(['news_item_id'], ['news_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('news_item_id')
    )
    op.create_index('ix_analysis_results_impact_magnitude', 'analysis_results', ['impact_magnitude'], unique=False)
    op.create_table('filter_results',
    sa.Column('news_item_id', sa.Text(), nullable=False),
    sa.Column('is_relevant', sa.Boolean(), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=False),
    sa.Column('reason', sa.Text(), server_default='', nullable=False),
    sa.Column('filtered_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['news_item_id'], ['news_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('news_item_id')
    )
    op.create_table('research_reports',
    sa.Column('news_item_id', sa.Text(), nullable=False),
    sa.Column('executive_summary', sa.Text(), server_default='', nullable=False),
    sa.Column('context', sa.Text(), server_default='', nullable=False),
    sa.Column('affected_securities', sa.Text(), server_default='', nullable=False),
    sa.Column('historical_precedent', sa.Text(), server_default='', nullable=False),
    sa.Column('bull_scenario', sa.Text(), server_default='', nullable=False),
    sa.Column('bear_scenario', sa.Text(), server_default='', nullable=False),
    sa.Column('recommended_actions', sa.Text(), server_default='', nullable=False),
    sa.Column('risk_factors', sa.Text(), server_default='', nullable=False),
    sa.Column('confidence', sa.Float(), server_default='0.0', nullable=False),
    sa.Column('full_report', sa.Text(), server_default='', nullable=False),
    sa.Column('market_data_snapshot', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('researched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('model_used', sa.String(length=100), server_default='', nullable=False),
    sa.ForeignKeyConstraint(['news_item_id'], ['news_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('news_item_id')
    )
    op.create_table('user_news_read',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('news_item_id', sa.Text(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'news_item_id')
    )
    op.create_table('user_preferences',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('feed_columns', postgresql.JSONB(astext_type=sa.Text()), server_default='["all", "watchlist", "critical"]', nullable=False),
    sa.Column('digest_frequency', sa.String(length=20), server_default='hourly', nullable=False),
    sa.Column('alert_schedule', postgresql.JSONB(astext_type=sa.Text()), server_default='{"start": "09:00", "end": "18:00", "timezone": "Asia/Shanghai"}', nullable=False),
    sa.Column('theme', sa.String(length=20), server_default='light', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('user_sources',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('source_type', sa.String(length=20), server_default='rss', nullable=False),
    sa.Column('priority', sa.String(length=5), server_default='p1', nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('watchlists',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_default', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('watchlist_items',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('watchlist_id', sa.UUID(), nullable=False),
    sa.Column('item_type', sa.String(length=20), nullable=False),
    sa.Column('value', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['watchlist_id'], ['watchlists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('watchlist_id', 'item_type', 'value', name='uq_watchlist_item')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('watchlist_items')
    op.drop_table('watchlists')
    op.drop_table('user_sources')
    op.drop_table('user_preferences')
    op.drop_table('user_news_read')
    op.drop_table('research_reports')
    op.drop_table('filter_results')
    op.drop_index('ix_analysis_results_impact_magnitude', table_name='analysis_results')
    op.drop_table('analysis_results')
    op.drop_table('alert_rules')
    op.drop_table('users')
    op.drop_index(op.f('ix_token_usage_timestamp'), table_name='token_usage')
    op.drop_index(op.f('ix_token_usage_stage'), table_name='token_usage')
    op.drop_table('token_usage')
    op.drop_table('source_health')
    op.drop_index(op.f('ix_news_items_source_name'), table_name='news_items')
    op.drop_index(op.f('ix_news_items_fetched_at'), table_name='news_items')
    op.drop_index(op.f('ix_news_items_content_hash'), table_name='news_items')
    op.drop_table('news_items')
    # ### end Alembic commands ###
